### PR TITLE
Raw binary string length

### PR DESCRIPTION
**Pull request by paragonie-scott**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Could you please provide a brief description what this function does and why it is needed?

Also, this package tries to be an exact backport of functions from higher PHP versions. Does this PR has effect on the expected behavior?

I see the purpose, but I would be happy to know what led to this solution.

Thanks for your contribution.

**Comment by paragonie-scott** [comment]
If you set `mbstring.func_overload = 7` in your php.ini file, `strlen()` and `substr()` (and many more functions) will be replaced by multibyte variants. The multibyte versions of these functions are unsuitable for cryptography operations which rely on raw binary strings.

This adds a specific function `hash_compat_strlen()` which will use `mb_strlen()` in `'8bit'` mode if the function is available. Otherwise, it falls back to the normal `strlen()` for backwards compatibility.

The end result of this PR is that your string lengths will always be accurate no matter how the server is configured. This issue was brought to our attention by @ircmaxell the author of many PHP security libraries.

**Comment by paragonie-scott** [comment]
Actually, this also affects `hash_pbkdf2()`. I wonder if I should make it a separate file?

**Comment by sagikazarmark** [comment]
Thank you very much for the explanation.

I wonder how this is solved in the original functions. Are you aware of this issue present in the original implementations? Or only the userland functions are affected?

Anyway, if both functions are affected then it should indeed go into a separate file. However the library advertises itself as "one function, one include" lib, so adding extra dependencies is something that I don't really like.

Here is a possible solution:
1. Put the following line in both files:

``` php
defined('MB_STRING_AVAILABLE') or define('MB_STRING_AVAILABLE', function_exists('mb_strlen'));
```

(Since we are in procedural context, I propose to replace the static variable solution with a constant based one. It is faster to test and nicer IMO)
1. Instead of defining a function, there could be a closure defined in both functions which does the job using the constant defined earlier. It is code duplication I know, but I think it is not that much code and we keep the package clean from unwanted dependencies, defined internal functions, etc.

What do you think?

**Comment by sagikazarmark** [comment]
We should probably pick a better name for MB_STRING_AVAILABLE

**Comment by sagikazarmark** [comment]
One more thing that came up: shouldn't we add some tests for such PHP environments? (I mean: run the existing tests in such environment)

Travis could do that

**Comment by sagikazarmark** [comment]
Further testing mbstring: I found that it is a bit slower than simple strlen. Always using it is probably not the best idea.

So the check would be modified to the following:

``` php
defined('USE_MB_STRING') or define('USE_MB_STRING', (ini_get('mbstring.func_overloead') > 0 and function_exists('mb_strlen')));
```

**Comment by ircmaxell** [comment]
I am hesitant to rely on `ini_get('mbstring.func_overload')`. Instead, I would suggest that you always use `mb_strlen($foo, '8bit')` if mbstring is present.

**Comment by sagikazarmark** [comment]
@ircmaxell thanks for joining the conversation.

Why is that? Are there any cases where we could get a false result? Or are there any cases where `ini_get` won't work/return the real setting?

**Comment by sagikazarmark** [comment]
@ircmaxell do you have a blog post or a public writting where you explain this issue?

**Comment by sagikazarmark** [comment]
Ok, I am going to merge this one and make the further changes myself.

@paragonie-scott Thank you very much for your contribution.

**Pull request merged**
